namespace WinRTCppRuntimeComponent {
    interface IShape {
        void Show();
        Single Area();
    }
    [default_interface]
    runtimeclass Circle : IShape {
        Single Radius { get; };
        Circle(Single radius);
    };
    [default_interface]
    runtimeclass Square : IShape{
        Single Size { get; };
        Square(Single size);
    };
}